apiVersion: v1
entries:
  clickhouse-exporter:
  - annotations:
      artifacthub.io/links: |
        - name: chart source
          url: https://github.com/almorgv/helm-charts/clickhouse-exporter
        - name: app source
          url: https://github.com/ClickHouse/clickhouse_exporter
        - name: image source
          url: https://github.com/flant/clickhouse_exporter
    apiVersion: v1
    appVersion: 0.2.1
    created: "2021-07-11T13:59:15.1584866+03:00"
    description: Clickhouse metrics exporter for Prometheus
    digest: 8cdf24a383ec5f3684ab8b7905d082aed1f4940745bca76cd233e245a8c7f347
    keywords:
    - metrics
    - clickhouse
    - monitoring
    kubeVersion: '>=1.14.0-0'
    maintainers:
    - email: almorgv@gmail.com
      name: almorgv
      url: https://github.com/almorgv
    name: clickhouse-exporter
    urls:
    - clickhouse-exporter-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    appVersion: 0.2.1
    created: "2021-07-11T13:59:15.1574844+03:00"
    description: Clickhouse metrics exporter for Prometheus
    digest: ae2671b6ee9edc888a6c064943afd1f68c9505f34e587007bee89e1e68e1a13a
    keywords:
    - metrics
    - clickhouse
    - monitoring
    kubeVersion: '>=1.14.0-0'
    name: clickhouse-exporter
    urls:
    - clickhouse-exporter-0.1.0.tgz
    version: 0.1.0
  gitlab-code-review-notifier:
  - annotations:
      artifacthub.io/links: |
        - name: chart source
          url: https://github.com/almorgv/helm-charts/gitlab-code-review-notifier
        - name: app source
          url: https://github.com/almorgv/gitlab-code-review-notifier
    apiVersion: v2
    appVersion: 0.1.0
    created: "2021-07-11T13:59:15.1905075+03:00"
    dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.5.2
    description: A Gitlab Code Review Notifier chart for Kubernetes
    digest: 8f964c43f655cf11f193383bce08d6de94120732b37be243259e56ebde8848f2
    home: https://github.com/almorgv/gitlab-code-review-notifier
    maintainers:
    - email: almorgv@gmail.com
      name: almorgv
      url: https://github.com/almorgv
    name: gitlab-code-review-notifier
    type: application
    urls:
    - gitlab-code-review-notifier-0.1.0.tgz
    version: 0.1.0
  pact-broker:
  - apiVersion: v2
    appVersion: 2.79.1.1
    created: "2021-07-11T13:59:15.2035154+03:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.4.6
    description: Pact Broker Helm chart for Kubernetes
    digest: 9b13177dabaac2ebc68431a8469e203f0a8c09793cb6046a860008bc5399b2af
    name: pact-broker
    type: application
    urls:
    - pact-broker-0.1.0.tgz
    version: 0.1.0
generated: "2021-07-11T13:59:15.1434375+03:00"
