apiVersion: v1
entries:
  clickhouse-exporter:
  - apiVersion: v1
    appVersion: 0.2.1
    created: "2021-06-18T18:52:00.2016052+03:00"
    description: Clickhouse metrics exporter for Prometheus
    digest: ae2671b6ee9edc888a6c064943afd1f68c9505f34e587007bee89e1e68e1a13a
    keywords:
    - metrics
    - clickhouse
    - monitoring
    kubeVersion: '>=1.14.0-0'
    name: clickhouse-exporter
    urls:
    - clickhouse-exporter-0.1.0.tgz
    version: 0.1.0
  pact-broker:
  - apiVersion: v2
    appVersion: 2.79.1.1
    created: "2021-06-18T18:52:00.2336265+03:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.4.6
    description: Pact Broker Helm chart for Kubernetes
    digest: 9b13177dabaac2ebc68431a8469e203f0a8c09793cb6046a860008bc5399b2af
    name: pact-broker
    type: application
    urls:
    - pact-broker-0.1.0.tgz
    version: 0.1.0
generated: "2021-06-18T18:52:00.2006042+03:00"
