{{- if and .Values.password (not .Values.passwordFromSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "clickhouse-exporter.fullname" . }}
  labels:
    app: {{ template "clickhouse-exporter.name" . }}
    chart: {{ template "clickhouse-exporter.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  clickhouse-password: {{ .Values.password | b64enc | quote }}
{{- end -}}