{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "clickhouse-exporter.fullname" . }}
  labels:
    chart: {{ template "clickhouse-exporter.chart" . }}
    app: {{ template "clickhouse-exporter.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
